### ISSUE TITLE
Some org members able to surpass metering limit

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1023]
Some CBC members are still uploading audio even though they're getting the "Over your limit" warning.

See: https://www.popuparchive.com/superadmin/monthly_usages/73209
They were at 51h this morning and now they're at 53h.

Also, I don't know what happens when you click "Save" and I don't want to add anything to their live account, but when I "viewed as" the guy who uploaded the last two hours, this is what I saw:
![screen shot 2015-02-27 at 2 34 18 pm](https://cloud.githubusercontent.com/assets/1718286/6422481/ecee925a-be8d-11e4-8752-d639175b6a6e.png)

**Comment by annewootton** [comment]
To clarify: the user in question is not an admin. https://www.popuparchive.com/superadmin/users/1599

**Comment by pkarman** [comment]
I get the same warning as that user. The 'Save' button is the only bug. I don't see how he would be able to add any more audio.

Is there a specific user that you think should not have been able to upload more audio and did?

**Comment by annewootton** [comment]
Yes, that user. He uploaded two hours today. He should not have been able
to.

**Comment by annewootton** [comment]
https://www.popuparchive.com/superadmin/transcripts/51896
https://www.popuparchive.com/superadmin/transcripts/51897
https://www.popuparchive.com/superadmin/transcripts/51898
https://www.popuparchive.com/superadmin/transcripts/51899

**Comment by pkarman** [comment]
It looks like his subscription changed yesterday:
https://www.popuparchive.com/superadmin/monthly_usages/73173

He has a bunch of premium transcripts flagged as belonging to a Community 1 plan.

Have we had any contact with this user? Any idea how his plan could be showing differently like that?

**Comment by pkarman** [comment]
actually it wasn't him, yesterday. it was the org, on or around 2015-02-18 03:00:48 UTC

https://www.popuparchive.com/superadmin/monthly_usages/73209

did we adjust their plan for some reason?

**Comment by pkarman** [comment]
ah I see what happened.

we deployed the change that attached specific subscription_plan ids to each transcript on or around Feb 18, so the ones showing the Org plan are actually null and showing the current Org plan, not the plan-at-time-of-transcript creation.

**Comment by annewootton** [comment]
Is the problem that transcripts from before 2/18/15 aren't being counted toward the current 50hr monthly limit, because they have "null" for subscription_plan id? 

Will this be fixed by the "assignment bug" you mentioned correcting in your local branch?

And the question remains: why are users for this org still seeing "You're over your limit!" alerts if somehow they are also able to upload audio?

**Comment by pkarman** [comment]
the subscription_plan_id assigned to each transcript has no affect on whether the transcript is counted toward monthly limits.

The fix I have ready will not affect this issue.

You ask the right question: how are people able to upload limits if they are seeing alerts about being over their limits. I don't yet know.
